name: Build Java Multistage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     -
      name: Checkout Code
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
 #   - name: Compile Java Code into Jar
#      run: docker build . --file build.Dockerfile --cache-from multi-stage-docker-build:ci --tag multi-stage-docker-build:ci
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build.Dockerfile
        tags: multi-stage-docker-build:ci
        outputs: type=docker,dest=/tmp/myimage.tar
#   - name: Package for next step
#     run: docker save multi-stage-docker-build:ci | gzip > build.tar.gz
    -
      name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: build-data
        path: /tmp/build.tar

  package:

    runs-on: ubuntu-latest

    needs: [build]

    steps:
      -
        name: Get Build Data
        uses: actions/download-artifact@v2
        with:
          name: build-data
          path: /tmp
      -
        name: Load Docker Image
        run: docker load --input tmp/build.tar
      -
        uses: actions/checkout@v2
      -
        name: Package Java into runtime
        run: docker build . --file runnable.Dockerfile --cache-from multi-stage-docker-build:ci --cache-from multi-stage-docker-runnable:ci --tag multi-stage-docker-runnable:ci
