name: Build Java Multistage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout Code
      uses: actions/checkout@v2
    -
      name: Compile Java into Jar file
      run: docker build . --file Dockerfile --cache-from multi-stage-docker-build:ci --tag multi-stage-docker-build:ci --target builder
    -
      name: Save docker image
      run: docker save --output /tmp/build.tar multi-stage-docker-build:ci
    -
      name: Send docker image to next stage
      uses: actions/upload-artifact@v2
      with:
        name: build-data
        path: /tmp/build.tar

  package:

    runs-on: ubuntu-latest

    needs: [build]

    steps:
      -
        name: Get docker image from previous stage
        uses: actions/download-artifact@v2
        with:
          name: build-data
          path: /tmp
      -
        name: Load docker image into local repo
        run: docker load --input /tmp/build.tar
      -
        name: Transfer Jar file into end enviroment
        run: docker build . --file Dockerfile --cache-from multi-stage-docker-build:ci --cache-from multi-stage-docker-runnable:ci --tag multi-stage-docker-runnable:ci
      -
        name: Save end docker image
        run: docker save --output /tmp/package.tar multi-stage-docker-runnable:ci
      -
        name: Upload docker image as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: package-data
          path: /tmp/package.tar

  run_on_server:

    runs-on: ubuntu-latest

    needs: [package]

    steps:
      -
        name: Get docker image from previous stage
        uses: actions/download-artifact@v2
        with:
          name: package-data
          path: /tmp
      -
        name: Load docker image into local repo
        run: docker load --input /tmp/package.tar
      -
        name: Run container
        run: docker run multi-stage-docker-runnable:ci
